version: '3.2'
services:

    icap-openmrs-tomcat:
        build:
            context: ./tomcat
        container_name: icap-openmrs-tomcat
        ports:
            - "8080:8080"
        networks: 
            - network
        depends_on: 
            - "icap-openmrs-mysql"
        volumes: 
          - type: bind
            source: /opt/openmrs/data/openmrswar
            target: /usr/local/tomcat/webapps 
          - type: bind
            source: /opt/openmrs/data/modules
            target: /usr/local/tomcat/.OpenMRS/modules
        restart: unless-stopped

    icap-openmrs-mysql:
        build: 
            context: ./database
        container_name: icap-openmrs-mysql
        ports: 
            - "3306:3306"
        networks: 
            - network
        volumes:
            - type: volume
              source: dbdata
              target: /opt/openmrs/data
        restart: unless-stopped

networks: 
  network:
    driver: bridge

volumes:
  dbdata:
